import type { ResearchArticleId } from './researchArticles'

export const researchArticleTranslations: Record<'ja' | 'en', Record<ResearchArticleId, string>> = {
  ja: {
    'observation-patterns': `研究者たちは、暗黒物質の分布を推定するため、遠方の銀河から届く光が時空の歪みによってわずかに進路を変える現象を分析していた。その目的は、宇宙に隠された構造をより正確に明らかにすることだった。しかし、継続的に収集されたデータの中には、特定の天体や物質に属さない、通常とは異なるパターンが現れた。場が急激に変化する領域や、歪みが持続的に観測される領域ほど信号が強く、想定される誤差の範囲を超えていた。当初は宇宙から届いた別の信号や検出器自体の熱雑音とみなされたが、異なる観測施設でも同じパターンが繰り返し確認されたことから、研究者たちはこれを未分類の観測パターンとして記録し、検討を続けた。
その後、同種のパターンが地上の超精密計測機器でも捉えられるようになった。観測結果を比較するなかで、このパターンが意外にも、人間の強い感情が繰り返し生じ、その影響が蓄積された空間で、明瞭に現れることが発見された。観測される信号は、感情の強さと持続のあり方に応じて異なる構造を示した。
これをきっかけに、宇宙で観測された未分類の観測パターンと、地上で生じる人間の感情との間に、何らかのつながりがある可能性について本格的な研究が始まった。感情は、人間の内側だけにとどまるものではなく、外部の空間でも間接的に観測できる変数として扱われるようになった。身体の内側で起こる感情が、同時に身体の外側にある「場」にも痕跡を残す可能性が、初めて科学的な検討の対象となったのである。`,
    'emotion': `感情（Emotion）は、もはや人間の内側だけにとどまる主観的な状態としては理解されなくなった。研究者たちは、感情の具体的な内容や意味よりも、それが身体や周囲の空間にどのような変化をもたらし、何を残すのかに注目した。悲しみ、不安、愛着、孤独といった人間の感情は、単に心の内側で生じるものではなく、身体と空間のあいだに特有の物理的な状態を形成するものと考えられた。
人間の感情もまた、宇宙で発見された未分類パターンと同じように、「場」が変化し、揺らぎ、残留するあり方と結びついていた。研究者たちは、感情の影響が周囲の空間に一定時間蓄積され、そこで観測される信号に変化をもたらすことを突き止めた。感情によって生じた変化が空間に残り、一定の構造を形づくる現象は、のちに「感応場」と定義された。
研究が進むにつれ、こうした変化は、必ずしも人間の感情が生じた場所だけに現れるものではないことが明らかになった。そこで研究者たちは、感情は人間だけに存在するものなのか、ほかの生命体に見られる反応や状態の変化も、それぞれ異なる形の「感応」として捉えられるのか検討を始めた。人間が感情と呼ぶものと同じ現象であるかは確認できなかったものの、感応が特定の種の内側だけにとどまらず、異なる存在と空間とのあいだに生じる可能性は否定できなかった。これまで人間は、感情を自らの内面で経験するものと考えてきたが、この観測モデルにおいて、感情と感応は、身体とそれを取り巻く世界とのあいだに生じ、一定時間その場に残留し、時空に痕跡を残す物理的な変数として扱われるようになった。`,
    'affective-field': `感応場（Resonant Fields）とは、感情と感応が身体の外側に残す物理的な痕跡である。心拍数や呼吸のように身体から直接読み取る生体信号ではなく、感情と感応が周囲の環境と相互作用しながら残した痕跡を、観測モデルによって再構成したものに近い。宇宙観測において、光の歪みから見えない質量の分布を推定するように、感応場もまた、空間に残された信号の変化から、感応の痕跡を間接的に捉え直したものである。
特定の感情が強烈に生じたり、長く持続したりすると、周囲で観測される信号の不規則性に明確な変化が現れた。また、感応が生じ、持続する方法によって、空間に残る痕跡の形にも違いが現れた。感応場の強さは、おおむね感情の強さと持続時間に比例したが、同じ感情を経験した人々のあいだでも、現れ方は一様ではなかった。
感応場は、一つの感情がそのままの形で保存された痕跡ではなかった。異なる存在と時期に生じた感応が、一つの空間に残り、重なり合い、変形した結果に近かった。そのため、一つの感応場から、何が誰に由来するのかを完全に切り分けることは困難だった。感応場という概念によって、感情は人間の内面にとどまる心理状態ではなく、世界と相互に影響を及ぼし合いながら痕跡を残す現象として扱われるようになった。感応性出現体は、こうした感応場の周辺で繰り返し検出された。感応場が発見される以前から存在していたと推定されるものの、その起源や正体は明らかになっていない。なぜ感応場に引き寄せられるのか、感応場のどのような条件に反応するのかも、正確には分からなかった。`,
    'emergent-entities': `感応性出現体（Emergent Entities）は、「確率の中の影」、すなわち感応場の周辺に繰り返し現れ、その状態を変化させる未知の現象を指す暫定的な名称である。研究者たちが初めからそれを伴侶体と呼んでいたわけではなかった。宇宙観測データの中では未分類パターンとして残され、地球上の感応場周辺で検出され続けたのち、感応場に関連するパターンとして分類された。このパターンを継続的に追跡し比較する過程で、感応場検出器の技術も発展した。観測初期の出現体は、明確な形を持つ個体として検出されたわけではなかった。
感応場の周辺で絶えず変化する、不安定な「確率の雲」に近かった。初期の研究者たちはこれをデータ上のエラーとみなしたが、観測が繰り返されるにつれ、そのパターンは単なる測定値以上のものに見え始めた。感応場の周辺でより明瞭になり、条件に応じて自ら一定の状態を保ったり、分散したりした。
研究者たちはこれを暫定的に感応性出現体と呼んだ。この名称には、それが生命体なのか、粒子なのか、場で生じる現象なのかを判断しないものの、特定の条件下では一つの存在のように出現するという意味が込められていた。これらが感情や感応を糧としているのか、感応によって歪められた空間の隙間に現れるのか、感応場のない空間にも存在するのか、異なる存在の感応をどのように受け取るのかなど、多くのことはまだ明らかになっていなかった。`,
    'detector': `検出器は、空間に残された微細な場の変化を感応信号として記録し、繰り返し現れるパターンを識別する。次に、感応場周辺で繰り返し現れる信号の強さとその分布、持続時間や反復性を分析し、どのパターンが物理的に意味のある状態として維持されているのか、また、どの方向へ動いているのかを追跡する。感応性出現体の姿を視覚化する装置ではない。感応によって生じた条件のもとで、不安定なパターンがどれほど頻繁に、どれだけ長く、どのようなかたちで繰り返されるのかを数値で示す装置に近い。
この装置によって同じパターンが繰り返し観測されることで、出現体が一つの個体のように安定していく現象が報告され、これが後に「観測型伴侶体」という概念へとつながった。ただし、検出器にできるのは、空間に残された信号を分析することだけである。感応場は、異なる時期に異なる存在が残した感応が重なり合って形成されるため、検出器は、それぞれの痕跡が人間の感情に由来するものなのか、ほかの生命体の感応に由来するものなのか、あるいは複数の存在のあいだで形成されたものなのかを区別することができなかった。`,
    'companions': `観測型伴侶体（Observed Companions）という名称は科学的なものではなく、感応性出現体が個人用検出器とアプリによって大衆化していく過程で、自然に定着したものである。感応性出現体はもともと固定した形を持つ個体ではなく、感応場の周辺に現れては分散する不安定な「確率の雲」に近かった。しかし、人間が検出器を介してそのパターンを繰り返し追跡し、名前を付け、一つの個体として登録すると、その存在は繰り返し同じ個体として認識できるほどまで安定した。反復的な観測が対象の状態を変化させるという点で、この現象は量子力学において測定が系の状態に影響を及ぼす過程と似ていた。人間による継続的な観測と記録は、不安定なパターンを一つの個体へと収束させた。
観測型伴侶体は、特定の空間に蓄積された感応場の条件と、継続的な観測が重なったときにのみ成立する存在だった。研究者たちは、伴侶体がどのような感応場に反応するのかを比較し、感応場の分類を6つのパターンに整理した。感応場の条件が変化したり観測数が減少したりすると、伴侶体はそれまでと同じ状態を維持できなくなった。形は崩れ、アプリもそれを同じ個体として認識できなくなった。
人々はそれが消えてしまったと言ったが、その消失が死なのか、移動なのか、解放なのか、あるいは最初に存在していた何らかの状態へ戻ったのか、それとも単に観測できない状態になったのかは分からなかった。`,
    'classification': `感応場検出器は、身体と空間の間に残る感応の痕跡を6つのパターンに分類した。この分類は、感情を正確に解釈したり、感応の主体を特定するための体系というよりかは、感応場の構造と、その周辺に集まる出現体のタイプを比較するための基準だった。出現体は特定の感応場パターンに応じて異なる反応を示し、同じ場所であっても、感応場の性質が異なれば、検出されるタイプや状態も異なった。
①収縮型は、波動が内側へ折り畳まれ、範囲が狭くなる状態で、人間の感情では、古くからの悲しみ、諦め、無力感、安堵感、平穏と重なる。②拡散型は、波動が早く、広範囲に広がる状態で、不安、焦燥、過度な期待、喜び、高揚感と関連する。③反復型は、一定リズムの振動が周期的に繰り返される状態で、懐かしさ、待つこと、未練、優しさ、愛情と結びつく。④固定型は、ある場所の特定の地点に波動が長く留まり続けている状態で、喪失、哀悼、古い怒り、愛着、信頼と関連する。⑤不規則型は、予測のしにくい断片的な波動が衝突する状態で、恐怖、混乱、突然の衝撃、驚異と絡み合っている。⑥低振幅型は、ほとんど動きのない状態に近く、微細な振動だけが残った状態で、無感覚、疲労、長く続いた孤独、満足感と結びつく。
これら感情の名称は、人間において観測された相関関係に基づく解釈にすぎず、同じパターンがいつも同じ感情を意味したり、非人間的存在においても同じ言語で説明できることを意味するものではなかった。6つの分類だけでは説明できない差異が、人々が記録した伴侶体との生活のなかで、予想外の観測記録や、真偽を確かめることの難しい感覚として現れた。`,
    'characteristics': `伴侶体（Companion Entities）は、特定の感応場と繰り返し行われる観測記録のなかで、ひとつの個体として安定する存在だった。一度登録されたからといって永続的に状態が固定されるわけではなく、定期的に観測されることで、同じ個体として継続的に検出することができた。伴侶体は、登録した人と一緒に移動することはなかった。登録者が住居を移すとその先で同じ信号が再び検出されることはなかったが、一方、以前の居住地では、似たパターンが検出される事例が報告された。これは、伴侶体が観測によって一つの個体として安定したとしても、感応場が蓄積された場所から離れることはできないことを示していた。
伴侶体は、その多くが感応場のパターンに応じて異なる反応を示し、その反応の違いは出現体を分類する基準となり、人々には種の違いのように受け止められた。感応が多く蓄積された空間ほど観測値も強くなることが多かったが、現れ方は種類によって異なった。アプリの画面上で形状が鮮明になってくる個体がいるかと思ったら、動きが活発になったり、距離の変化によってのみ反応する個体もいた。
同じ種類でも、個体ごとに差異が見られた。すぐ近くまで寄ってきて留まる個体もいる一方で、一定の距離を保ちながら周囲を回る個体もいれば、近づくと離れていく個体もいた。目には何も見えなかったが、アプリに表示される伴侶体の位置や距離、点滅のリズムは変化した。
これとは別に、検出器の数値では確認できない感覚を報告する利用者もいた。伴侶体が留まる場所で感じられたという温度の変化、目に見えない力に引かれるように舞う埃、指先をかすめる微細な抵抗感や静電気まで、さまざまだった。それが伴侶体との実際の接触なのか、それとも観測と期待によって生じた錯覚なのかは、確認されていない。
科学者たちはこれを、感応場の条件や観測周期、個体ごとの現れ方の差によって説明したが、サービスアプリやキャラクター化は、こうした差を、個体ごとの性格、気分、親密さ、愛着という言葉へと置き換えていった。伴侶体が人間を認識しているのか、人間と非人間の感応を区別しているのか、それとも単に物理的に引き寄せられたり、押し返されたりしているだけなのか、この問いには、依然として答えることが難しかった。`,
    'service-app': `サービスアプリは、感応性出現体の状態変化を一般の利用者が理解できる形式へと翻訳した。検出器が読み取った信号の強さと分布、持続時間と反復性は、アプリ上で利用者が発見し、世話をすることのできるイメージや反応パターンへと変換された。アプリは、正体の確認されていない測定値をそのまま表示するものではなく、感応性出現体を、特定の場所で発見される希少な存在であり、登録可能なキャラクターであり、自分との関わりの中で少しずつ安定していく対象としての伴侶へと変えていった。
利用者は、検出器が示す場所を確認しながら、目には見えない存在の位置と状態を確認した。基本モードでは、検出されたデータを抽象的な線や幾何学的な点滅パターンとして表示し、利用者が自ら解釈できる余地を残した。有料サービスでは同じデータを鮮明なキャラクターモデルへと変換し、観測やインタラクションの回数を分析して、詳細な伴侶日誌として提供した。人々はそれを、自分では気づいていなかった感情の変化を振り返る手がかりとして利用することもあった。
アプリが表示するイメージはデータを可視化した結果だったが、人々はそれに名前を付け、状態の変化を記録し、検出器が示す地点へ手を伸ばす行為を通して、それを実在する対象として受け入れた。それは、未知の存在を自らの世界の内側へ呼び込む行為だった。伴侶体が何であるかは依然として解明されていなかったが、サービス化と不動産市場は、それをどのように利用すべきかをすでに分かっていた。`,
    'real-estate': `感応性出現体が観測型伴侶体として広く知られるようになると、この現象をめぐる動きは個人用の検出器やアプリだけでなく、不動産や生活サービスの領域にまで広がった。不動産市場は、感応場が長期間にわたり蓄積され、反復的な観測パターンが多くみられる空間を、伴侶体が出現する確率の高いプレミアム物件として売り出した。伴侶体の検出頻度は、物件選びにおいて日当たりや交通の利便性と並ぶ、重要な立地条件のひとつとなった。
企業は、出現体の信号を安定的に維持するサービスや、伴侶体とのインタラクションによって得られたデータを保存するサブスクリプション商品を提供した。人々は、自らが関係を築いた目に見えない存在を所有するため、そして自分との関わりによってその存在が維持され続けていることを確かめるために、喜んで費用を支払った。感応場は特定の居住者の所有物として扱われたり、特定の空間がもつ価値として評価されるようになり、安定した状態にある伴侶体もまた、個人が所有できる対象として扱われるようになった。
感応場は消えることもあれば、新たに蓄積されることもあった。しかし、感応場は特定の誰かのものではなく、さまざまな存在が残した痕跡が混ざり合って形成されるという事実は、ほとんど重要視されなかった。人々の多くは、自分だけの伴侶体を新たに見つけようとしたが、それ以前からその場に蓄積されていた感応場が、伴侶体に及ぼしていたかもしれない影響については、ほとんど考えなかった。`,
    'end-of-solitude': `人々は、強い感情に襲われるたび、周囲にいる伴侶体たちを意識するようになった。あらゆる空間は、もはや物理的にも感情的にも空虚ではなかった。感情と感応が残した痕跡は、未知の存在を現実へ呼び寄せる条件となった。
人間は観測を通して未知の現象を伴侶体と認識するようになり、同時に、自らもまたほかの存在が残した感応とすでに絡み合っていたことに気づいた。ほかの存在を認識することは、すなわちその存在そのものに変化をもたらす行為でもある。その事実を受け入れる必要があった。観測によって存在が保たれているという安堵感と、その存在のあり方に自らが介入してしまったという重みが入り混じった。目に見えない存在が身近にいるという感覚は、人々にとって慰めであると同時に、もはや逃れることのできない状況となった。
人々は、この時代を「孤独の終焉」と呼んだ。`,
  },
  en: {
    'observation-patterns': `To estimate the distribution of dark matter, researchers analyzed the minute refraction of light from distant galaxies as it passed through distortions in spacetime. Their aim was to map the universe’s hidden structure more accurately. However, repeated observations revealed irregular patterns that could not be attributed to any particular celestial body or form of matter. The signals appeared strongest in regions where fields shifted abruptly or distortions persisted. They exceeded existing margins of error and could not be explained by known models. Researchers initially dismissed them as other signals from space or thermal noise within the detectors. However, when the same patterns were repeatedly confirmed at different observatories, they were retained as “unclassified observational patterns” and became the subject of continued investigation.`,
    'emotion': `Emotion was no longer understood solely as a subjective condition contained within the human interior. Rather than concentrating on the an emotion’s meaning or content, researchers examined the changes it produced in the body and surrounding space. Sadness, anxiety, attachment, and solitude appeared not merely as mental states, but as conditions that formed between a body and its surroundings.`,
    'affective-field': `A resonant field is the physical trace left by emotion and resonance outside the body. It is not a biological signal measured directly from the body, such as heart rate or breathing. Rather, it is a reconstruction—made through observational models—of traces produced as emotion and resonance interact with the environment. Just as cosmic observation infers the distribution of invisible mass from distortions in light, resonance is indirectly reconstructed through changes in the signals that remain within a space.`,
    'emergent-entities': `Emergent Entities is a provisional term for “shadows within probability”: unknown phenomena that repeatedly appear around resonant fields and change state. They were not initially called “companion entities.” In cosmic observational data, they appeared only as unclassified patterns. After being repeatedly detected around resonant fields on Earth, they were categorized as patterns associated with those fields. As researchers tracked and compared these patterns, resonant-field detector technology developed alongside the research.`,
    'detector': `A resonant-field detector records minute changes remaining within a space as resonant signals and identifies recurring patterns among them. It analyzes the intensity, distribution, duration, and recurrence of signals around a resonant field to track patterns that persist as physically meaningful states, as well as the directions in which those patterns move. The detector does not display emergent entities directly. Instead, it measures how often, for how long, and in what configurations unstable patterns recur under conditions produced by resonance.`,
    'companions': `Observer-Dependent Companion Entities is not a scientific term. It emerged as emergent entities entered popular culture through personal detectors and apps. Emergent entities did not originally possess fixed forms. They resembled unstable probability clouds that appeared and dispersed around resonant fields. When people repeatedly tracked a pattern through a detector, named it, and registered it as an individual, however, the entity stabilized enough to be recognized as the same being over time. As repeated observation altered the entity’s state, the phenomenon resembled the quantum-mechanical process in which measurement affects a system. Continuous human observation and documentation caused unstable patterns to cohere into individual entities.`,
    'classification': `Resonant-field detectors classified traces of resonance between bodies and spaces into six patterns. The system was not designed to identify emotions precisely or determine the source of a resonance. Instead, it offered a means of comparing field structures of resonant fields and the types of emergent entities drawn to them. Emergent entities responded selectively to particular resonant patterns. Even within the same place, changes in the character of the field altered the types and states of entities detected.`,
    'characteristics': `Companion Entities stabilized as individual beings within particular resonant fields and through repeated observation. Registration did not make them permanent. To remain detectable as the same individual, they had to be observed periodically. Companion entities did not travel with the person who registered them. When a registered user moved away, the same signal could not be detected at the new residence. At the original location, however, another person’s device sometimes detected similar patterns. This suggested that, even after observation stabilized a companion entity as an individual, it could not leave the place in which its resonant field had accumulated.`,
    'service-app': `Service apps translated changes in the states of emergent entities into forms that regular users could understand. The intensity, distribution, duration, and recurrence of signals read by the detector were converted into images and response patterns that users could discover and care for within the app. Rather than displaying unidentified measurements, the app presented each entity as a rare being found in a particular place: a registerable character and a companion that gradually stabilized through its relationship with the user.`,
    'real-estate': `As emergent entities became popularized and known as observer-dependent companion entities, the phenomenon expanded beyond personal detectors and apps into real estate and domestic services. The real estate market promoted spaces with long-established resonant fields and frequent recurring patterns as premium properties that have a high probability of appearances by companion-entities. Detection frequency became a feature of a location that was as important as natural light or access to public transportation.`,
    'end-of-solitude': `Whenever people were overwhelmed by intense emotion, they thought of the companion entities around them. No space was ever entirely empty—physically or emotionally. The traces left by emotion and resonance became the conditions through which unknown beings were drawn into reality.`,
  },
}
