import type { Language } from '../store/experienceStore'

export const researchSubtitles: Record<Language, string[]> = {
  ko: [
    '먼 곳을 바라보던 인간은 자신에게 가장 내밀한 것과 닮은 무언가와 마주했다.',
    '은하에서 온 빛의 미세한 굴절을 분석하던 연구자들은 어떤 천체나 물질의 신호로도 설명되지 않는 패턴을 발견했다.',
    '이후 지구의 계측 장비에서도 그와 닮은 구조가 포착되었고, 인간의 강한 감정 변화와 높은 연관성을 보였다.',
    '이 발견을 계기로 감정은 개인의 내면에 국한된 것이 아니라, 몸 밖의 공간에도 흔적을 남기는 현상으로 다뤄지기 시작했다.',
    '연구자들은 감정이 공간에 쌓이고 겹쳐 형성된 장을 감응장이라 불렀다.',
    '그러나 감응장이 인간의 감정만으로 형성되는지, 다른 존재에게도 영향을 받는지, 우주에서 발견된 패턴과 어떤 관련이 있는지는 여전히 알 수 없었다.',
    '감응장 주변에서는 미지의 출현체가 반복적으로 검출되었다.',
    '감응장의 성격에 따라 서로 다른 유형의 출현체가 모여들었다.',
    '출현체는 기존의 어떤 생물종으로도 분류되지 않았으며, 아마도 이전부터 존재해온 것으로 추정되었다.',
    '이들이 무엇인지, 왜 감응장에 이끌리는지는 밝혀지지 않았다.',
    '연구자들은 공간에서 일어나는 여러 변화를 측정하고, 그 안에서 반복되는 패턴을 통해 출현체의 상태를 간접적으로 재구성했다.',
    '검출기는 측정값을 통해 출현체의 상태를 패턴으로 재구성했지만, 그것이 어떤 모습인지는 알 수 없었다.',
    '관측이 거듭될수록 불안정했던 출현체의 패턴은 점차 일관성을 보이기 시작했다.',
    '관측이 줄거나 감응장의 조건이 달라지면 형태가 변하거나 패턴이 약해졌고, 다시 분산되기도 했다.',
    '출현체의 정체가 충분히 밝혀지기 전에 개인용 반려체 검출기와 서비스 앱이 보급되었다.',
    '사람들은 이들을 반려체라 부르기 시작했다.',
    '서비스 앱은 반려체의 상태를 사람들이 이해할 수 있는 방식으로 번역했다.',
    '신호의 세기와 지속 시간, 점멸과 거리의 변화는 성격과 기분, 친밀도와 애착의 언어로 바뀌었고, 미지의 현상은 화면 속에서 발견하고 돌볼 수 있는 캐릭터가 되었다.',
    '이 과정을 거치며 반려체는 인간이 알아볼 수 있는 특정한 모습으로 좁혀졌다.',
    '사람들은 반려체에 이름을 붙이고 상태 변화를 기록하며 검출기가 가리키는 지점에 손을 뻗었다.',
    '그 행위에는 다정함과 간섭이 함께 있었다.',
    '반려체가 대중화되면서 이 현상은 부동산과 서비스의 영역으로 확장되었다.',
    '반려체는 특정한 장소에 축적된 감응장의 결에 귀속되어 있었다.',
    '등록자가 다른 거주지로 떠나면 같은 반려체를 다시 검출할 수 없었다.',
    '특정 공간의 반복적인 검출 기록은 반려체의 출현 가능성을 보여주는 지표가 되었고, 부동산 시장은 출현체가 자주 검출되는 공간을 프리미엄 매물로 내세웠다.',
    '감응장은 공간의 가치로 환산되었고, 반려체는 개인이 등록하고 관리하는 대상이 되었다.',
    '기업들은 반려체의 관측 기록, 상호작용 데이터, 캐릭터 모델을 저장하는 구독 상품을 판매했다.',
    '미지의 존재를 알아보기 위해 만들어진 번역과 기록은 돌봄의 방식인 동시에 소유의 수단이 되었다.',
    '사람들은 어떤 공간도 완전히 비어 있지 않다는 것을 깨달았다.',
    '인간은 이미 다른 존재들의 감응과 얽혀 있었고, 검출기가 있든 없든 누구도 그 얽힘에서 완전히 벗어날 수 없었다.',
    '알아보는 일은 존재의 조건을 바꾸었다.',
    '누구도 자신을 세계의 바깥에 둘 수 없었다.',
    '사람들은 이 시대를 고독의 종말이라 불렀다.',
  ],
  ja: [
    '遠くを見つめていた人間は、自らの最も内密なものに似た何かと出会った。',
    '銀河から届く光の微細な屈折を分析していた研究者たちは、どの天体や物質の信号でも説明できないパターンを発見した。',
    'その後、地球上の計測機器でもそれに似た構造が捉えられ、人間の激しい感情変化と高い相関を示した。',
    'この発見を機に、感情は個人の内面に限られず、身体の外の空間にも痕跡を残す現象として扱われ始めた。',
    '研究者たちは、感情が空間に蓄積し重なって形成された場を感応場と呼んだ。',
    'しかし感応場が人間の感情だけで形成されるのか、他の存在からも影響を受けるのか、宇宙で発見されたパターンとどう関わるのかは、今なお分かっていない。',
    '感応場の周辺では、未知の出現体が繰り返し検出された。',
    '感応場の性質に応じて、異なる種類の出現体が集まった。',
    '出現体は既存のどの生物種にも分類されず、おそらく以前から存在していたと推測された。',
    'それらが何であり、なぜ感応場に引き寄せられるのかは解明されていない。',
    '研究者たちは空間で起こる複数の変化を測定し、そこで反復するパターンから出現体の状態を間接的に再構成した。',
    '検出器は測定値から出現体の状態をパターンとして再構成したが、それがどのような姿なのかは分からなかった。',
    '観測が重なるほど、不安定だった出現体のパターンは次第に一貫性を示し始めた。',
    '観測が減ったり感応場の条件が変わると、形が変化し、パターンが弱まり、再び分散することもあった。',
    '出現体の正体が十分に解明される前に、個人用の伴侶体検出器とサービスアプリが普及した。',
    '人々はそれらを伴侶体と呼び始めた。',
    'サービスアプリは、伴侶体の状態を人々が理解できる方法へ翻訳した。',
    '信号の強度と持続時間、点滅と距離の変化は、性格や気分、親密さや愛着の言葉へ変わり、未知の現象は画面の中で発見し世話のできるキャラクターになった。',
    'この過程を経て、伴侶体は人間が認識できる特定の姿へと絞り込まれた。',
    '人々は伴侶体に名前をつけ、状態の変化を記録し、検出器が示す地点へ手を伸ばした。',
    'その行為には、優しさと干渉が共に含まれていた。',
    '伴侶体が普及すると、この現象は不動産とサービスの領域へ拡大した。',
    '伴侶体は、特定の場所に蓄積した感応場の性質に結びついていた。',
    '登録者が別の住居へ移ると、同じ伴侶体を再び検出することはできなかった。',
    '特定空間での反復検出記録は伴侶体の出現可能性を示す指標となり、不動産市場は出現体が頻繁に検出される空間をプレミアム物件として売り出した。',
    '感応場は空間の価値へ換算され、伴侶体は個人が登録し管理する対象になった。',
    '企業は伴侶体の観測記録、相互作用データ、キャラクターモデルを保存する定額商品を販売した。',
    '未知の存在を認識するために作られた翻訳と記録は、世話の方法であると同時に所有の手段となった。',
    '人々は、どの空間も完全には空ではないと気づいた。',
    '人間はすでに他の存在の感応と絡み合っており、検出器の有無にかかわらず、誰もその絡み合いから完全には逃れられなかった。',
    '認識することは、存在の条件を変えた。',
    '誰も自らを世界の外側に置くことはできなかった。',
    '人々はこの時代を孤独の終わりと呼んだ。',
  ],
  en: [
    'Looking into the distance, humanity encountered something resembling its most intimate self.',
    'While analyzing the minute refraction of light arriving from galaxies, researchers discovered a pattern that could not be explained as the signal of any celestial body or substance.',
    'A similar structure was later captured by instruments on Earth, where it showed a strong correlation with intense changes in human emotion.',
    'This discovery led emotion to be treated not as something confined to an individual interior, but as a phenomenon that also leaves traces in spaces outside the body.',
    'Researchers called the field formed as emotions accumulated and overlapped in space a resonant field.',
    'Yet it remained unknown whether resonant fields were formed by human emotion alone, whether other beings also affected them, or how they related to the pattern discovered in space.',
    'Unknown emergent entities were repeatedly detected around resonant fields.',
    'Different types of emergent entities gathered according to the character of each resonant field.',
    'The entities could not be classified as any known species and were presumed to have existed long before their discovery.',
    'What they were, and why they were drawn to resonant fields, remained unknown.',
    'Researchers measured multiple changes occurring in a space and indirectly reconstructed the entities’ states through recurring patterns within them.',
    'The detector reconstructed an entity’s state as a pattern from its measurements, but could not reveal what the entity looked like.',
    'As observation continued, the once-unstable patterns of the entities gradually began to show consistency.',
    'When observations declined or the conditions of a resonant field changed, their forms shifted, their patterns weakened, and they sometimes dispersed again.',
    'Before the nature of the entities had been sufficiently established, personal companion detectors and service apps became widespread.',
    'People began to call them companions.',
    'Service apps translated the condition of companions into forms people could understand.',
    'Signal strength and duration, blinking, and changes in distance became the language of personality, mood, intimacy, and attachment, turning an unknown phenomenon into a character that could be found and cared for on a screen.',
    'Through this process, companions were narrowed into specific forms that humans could recognize.',
    'People named their companions, recorded changes in their condition, and reached toward the points indicated by their detectors.',
    'That gesture contained tenderness and interference at once.',
    'As companions became widespread, the phenomenon expanded into real estate and commercial services.',
    'A companion belonged to the particular grain of a resonant field accumulated in a specific place.',
    'When its registrant moved to another home, the same companion could no longer be detected.',
    'Repeated detection records in a space became an index of the likelihood of a companion appearing, and the real-estate market promoted spaces where entities were frequently detected as premium properties.',
    'Resonant fields were converted into spatial value, and companions became objects for individuals to register and manage.',
    'Companies sold subscriptions that stored observation records, interaction data, and character models for companions.',
    'The translations and records created to recognize unknown beings became both a form of care and a means of ownership.',
    'People realized that no space was ever completely empty.',
    'Humans were already entangled with the resonances of other beings, and with or without a detector, no one could fully escape that entanglement.',
    'The act of recognition changed the conditions of existence.',
    'No one could place themselves outside the world.',
    'People called this era the end of solitude.',
  ],
}
