import type { Language } from '../store/experienceStore'

export const researchSubtitles: Record<Language, string[]> = {
  ko: [
    '연구는 우주 관측 데이터와 미분류 관측 패턴에서 시작되었다.',
    '연구자들은 우주 관측 데이터에서 기존 모델로 설명할 수 없는 신호를 발견했다.',
    '특정 천체나 물질에 속하지 않은 신호였다.',
    '장의 변화가 크거나 왜곡이 오래 남을수록 강해졌다.',
    '이후 지구의 정밀 계측 장비에서도 비슷한 신호가 검출되었다.',
    '일부 신호는 인간의 강한 감정 변화와 높은 연관성을 보였다.',
    '연구가 확장되면서 감정과 비인간의 감응에 관한 새로운 가설이 등장했다.',
    '인간이 아닌 생명체와 환경에서도 유사한 변화가 발견된 것이다.',
    '감정은 더 이상 인간의 내면에만 머무는 상태가 아니었다.',
    '서로 다른 존재와 공간 사이에서 발생하고 주변에 흔적을 남기는 현상으로 다뤄지기 시작했다.',
    '이렇게 몸 바깥에 남은 감정과 감응의 흔적은 감응장이라 불렸다.',
    '감응장은 하나의 감정이 그대로 저장된 흔적이 아니었다.',
    '서로 다른 존재가 남긴 감응이 한 공간에 쌓이고 뒤섞인 결과였다.',
    '온도와 습도, 빛과 소리 같은 환경도 흔적이 남고 이동하는 방식에 영향을 미쳤다.',
    '따라서 하나의 감응장이 누구에게서 시작되었는지는 분리하기 어려웠다.',
    '감응장 주변에서는 정체를 알 수 없는 패턴이 반복적으로 나타났다.',
    '연구자들은 이 현상을 감응성 출현체라고 명명했다.',
    '감응성 출현체는 고정된 형태의 생명체라기보다 입자와 파동의 성질을 함께 보이는 불안정한 확률 구름에 가까웠다.',
    '감응장이 출현체를 만들어내는지, 이미 존재하던 무언가가 감응장에 이끌리는지는 아직 밝혀지지 않았다.',
    '감응장과 출현체의 상태를 추적하기 위해 감응장 검출기가 개발되었다.',
    '감응장 검출기는 온도와 전자기적 간섭, 신호의 세기와 지속 시간, 반복성을 분석했다.',
    '그러나 신호가 인간에게서 시작되었는지, 다른 생명체나 환경에서 발생했는지는 구분하지 못했다.',
    '반복해서 관측된 출현체는 점차 하나의 개체처럼 유지되기 시작했다.',
    '사람들은 이러한 존재를 관측형 반려체라고 불렀다.',
    '관측형 반려체는 처음부터 고정된 존재가 아니었다.',
    '특정한 장소의 감응장과 인간의 관측, 기록, 명명이 겹치면서 하나의 개체로 안정되었다.',
    '관측이 중단되거나 공간의 조건이 달라지면 다시 흩어진 파동 상태로 돌아갔다.',
    '그것이 사라진 것인지, 단지 관측할 수 없게 된 것인지는 알 수 없었다.',
    '출현체가 나타나고 흩어지는 방식을 비교하기 위해 감응장의 분류 체계도 만들어졌다.',
    '감응장은 수축형, 확산형, 반복형, 고정형, 불규칙형, 저진폭형으로 나뉘었다.',
    '각 유형은 슬픔과 불안, 그리움과 상실, 공포와 고독 같은 인간의 감정과 연결되었다.',
    '하지만 이는 인간의 관측을 기준으로 한 해석이었다.',
    '같은 분류로 비인간 존재의 상태까지 설명할 수 있는지는 알 수 없었다.',
    '관측이 쌓이면서 반려체의 특성도 조금씩 알려지기 시작했다.',
    '어떤 반려체는 형상이 선명해졌고, 어떤 반려체는 움직임이나 거리로 반응했다.',
    '관측값이 강해지면 현실 공간에 작은 간섭을 일으키기도 했다.',
    '국소적인 온도 변화, 전자기기의 잡음, 허공을 맴도는 먼지의 궤도, 손끝에 닿는 미세한 저항감이 나타났다.',
    '하지만 이것이 인간을 인식한 반응인지 단순한 물리적 현상인지는 밝혀지지 않았다.',
    '서비스 앱과 캐릭터화는 이 불확실한 현상을 사람들이 이해할 수 있는 모습으로 바꾸었다.',
    '검출된 신호는 선과 점멸 패턴으로 시각화되었다.',
    '유료 서비스에서는 선명한 캐릭터의 모습으로 변환되었다.',
    '사람들은 반려체에 이름을 붙이고 상태 변화를 기록했다.',
    '과학적으로 설명되지 않은 변화는 성격과 기분, 친밀도와 애착의 언어로 번역되었다.',
    '미지의 현상은 발견하고 돌볼 수 있는 반려 대상이 되었다.',
    '반려체가 대중화되면서 서비스화와 부동산의 영역도 빠르게 확장되었다.',
    '감응장이 오래 유지되는 집은 프리미엄 매물로 거래되었다.',
    '반려체의 신호와 상호작용 기록을 보존하는 유료 서비스도 등장했다.',
    '여러 존재가 남긴 감응장은 특정한 거주자와 공간의 자산으로 환산되었다.',
    '관측을 통해 안정된 반려체 역시 개인이 소유할 수 있는 대상으로 취급되었다.',
    '사람들은 이제 어떤 공간도 완전히 비어 있지 않다고 생각했다.',
    '감정과 감응이 남긴 흔적은 보이지 않는 존재를 현실로 불러냈다.',
    '인간 역시 수많은 존재의 흔적과 영향을 주고받는 연결망의 일부였다.',
    '관측은 미지의 존재를 알아보는 일이었다.',
    '동시에 그 상태를 바꾸는 개입이기도 했다.',
    '보이지 않는 존재가 곁에 있다는 감각은 위안이면서도 벗어날 수 없는 조건이 되었다.',
    '사람들은 이 시대를 고독의 종말이라고 불렀다.',
  ],
  ja: [
    '研究は宇宙観測データと未分類の観測パターンから始まった。',
    '研究者たちは宇宙観測データの中に、既存のモデルでは説明できない信号を発見した。',
    'それは特定の天体や物質に属さない信号だった。',
    '場の変化が大きく、歪みが長く残るほど信号は強くなった。',
    'その後、地球上の精密計測機器でも類似した信号が検出された。',
    '一部の信号は、人間の激しい感情変化と高い相関を示した。',
    '研究が広がるにつれ、感情と非人間的な感応に関する新たな仮説が現れた。',
    '人間以外の生命や環境でも、同様の変化が発見されたのである。',
    '感情はもはや、人間の内面だけに留まる状態ではなかった。',
    '異なる存在と空間の間に生じ、周囲に痕跡を残す現象として扱われ始めた。',
    'こうして身体の外に残った感情と感応の痕跡は、感応場と呼ばれた。',
    '感応場は、ひとつの感情がそのまま保存された痕跡ではなかった。',
    '異なる存在が残した感応が、ひとつの空間に積み重なり混ざり合った結果だった。',
    '温度や湿度、光や音などの環境も、痕跡が残り移動する方法に影響した。',
    'そのため、ひとつの感応場が誰から始まったのかを切り分けることは難しかった。',
    '感応場の周辺では、正体不明のパターンが繰り返し現れた。',
    '研究者たちはこの現象を感応性出現体と名づけた。',
    '感応性出現体は固定した生命体というより、粒子と波の性質を併せ持つ不安定な確率雲に近かった。',
    '感応場が出現体を生むのか、既に存在する何かが感応場に引かれるのかは、まだ解明されていない。',
    '感応場と出現体の状態を追跡するため、感応場検出器が開発された。',
    '検出器は温度と電磁的干渉、信号の強度と持続時間、反復性を分析した。',
    'しかし信号が人間に由来するのか、他の生命や環境から生じたのかは区別できなかった。',
    '繰り返し観測された出現体は、次第にひとつの個体のように保たれ始めた。',
    '人々はそのような存在を観測型伴侶体と呼んだ。',
    '観測型伴侶体は、初めから固定された存在ではなかった。',
    '特定の場所の感応場に、人間の観測、記録、命名が重なることで、ひとつの個体として安定した。',
    '観測が途絶えたり空間の条件が変わると、再び散らばった波の状態に戻った。',
    'それが消えたのか、ただ観測できなくなったのかは分からなかった。',
    '出現体が現れ散らばる方法を比較するため、感応場の分類体系も作られた。',
    '感応場は収縮型、拡散型、反復型、固定型、不規則型、低振幅型に分けられた。',
    '各類型は悲しみと不安、恋しさと喪失、恐怖と孤独といった人間の感情に結びつけられた。',
    'しかしそれは、人間の観測を基準にした解釈だった。',
    '同じ分類で非人間的存在の状態まで説明できるかは分からなかった。',
    '観測が蓄積するにつれ、伴侶体の特性も少しずつ知られ始めた。',
    '姿が鮮明になる伴侶体もいれば、動きや距離で反応するものもいた。',
    '観測値が強まると、現実空間に小さな干渉を起こすこともあった。',
    '局所的な温度変化、電子機器の雑音、宙を漂う塵の軌道、指先に触れる微かな抵抗が現れた。',
    'しかしそれが人間を認識した反応なのか、単なる物理現象なのかは判明していない。',
    'サービスアプリとキャラクター化は、この不確かな現象を人々が理解できる姿へ変えた。',
    '検出された信号は、線と点滅パターンとして可視化された。',
    '有料サービスでは、鮮明なキャラクターの姿へ変換された。',
    '人々は伴侶体に名前をつけ、状態の変化を記録した。',
    '科学的に説明できない変化は、性格や気分、親密さや愛着の言葉へ翻訳された。',
    '未知の現象は、発見し世話をすることのできる伴侶対象になった。',
    '伴侶体が普及すると、サービス化と不動産の領域も急速に拡大した。',
    '感応場が長く維持される家は、プレミアム物件として取引された。',
    '伴侶体の信号と相互作用の記録を保存する有料サービスも登場した。',
    '複数の存在が残した感応場は、特定の居住者と空間の資産へ換算された。',
    '観測によって安定した伴侶体も、個人が所有できる対象として扱われた。',
    '人々は今や、どの空間も完全には空ではないと考えた。',
    '感情と感応が残した痕跡は、見えない存在を現実へ呼び出した。',
    '人間もまた、多くの存在の痕跡と影響を交換するネットワークの一部だった。',
    '観測とは、未知の存在を認識することだった。',
    '同時に、その状態を変える介入でもあった。',
    '見えない存在が傍らにいる感覚は、慰めであると同時に逃れられない条件となった。',
    '人々はこの時代を、孤独の終わりと呼んだ。',
  ],
  en: [
    'The research began with astronomical observation data and unclassified observational patterns.',
    'Researchers discovered signals in astronomical data that existing models could not explain.',
    'The signals belonged to no particular celestial body or substance.',
    'They grew stronger when changes in the field were greater or distortions remained longer.',
    'Similar signals were later detected by precision instruments on Earth.',
    'Some signals showed a strong correlation with intense changes in human emotion.',
    'As the research expanded, a new hypothesis emerged concerning emotion and nonhuman resonance.',
    'Similar changes had been found in nonhuman life and in the environment.',
    'Emotion was no longer understood as a state confined to the human interior.',
    'It began to be treated as a phenomenon arising between different beings and spaces, leaving traces around them.',
    'These traces of emotion and resonance outside the body came to be called resonant fields.',
    'A resonant field was not the preserved imprint of a single emotion.',
    'It was the result of resonances left by different beings accumulating and mixing within one space.',
    'Temperature, humidity, light, and sound also affected how traces remained and moved.',
    'It was therefore difficult to isolate who or what had initiated a resonant field.',
    'Unidentified patterns repeatedly appeared around resonant fields.',
    'Researchers named this phenomenon a resonant emergent entity.',
    'Rather than a life-form with a fixed shape, it resembled an unstable probability cloud with the properties of both particles and waves.',
    'It remains unknown whether resonant fields create the entities or whether something already present is drawn toward the fields.',
    'Resonant-field detectors were developed to track the conditions of the fields and the entities.',
    'The detectors analyzed temperature, electromagnetic interference, signal strength, duration, and recurrence.',
    'They could not distinguish whether a signal began in a human, another living being, or the environment.',
    'Entities observed repeatedly gradually began to persist like individual organisms.',
    'People called these beings observational companions.',
    'An observational companion was not a fixed being from the beginning.',
    'It stabilized as an individual when a place\'s resonant field overlapped with human observation, documentation, and naming.',
    'When observation ceased or spatial conditions changed, it returned to a dispersed wave state.',
    'No one knew whether it had disappeared or had merely become impossible to observe.',
    'A classification system for resonant fields was created to compare how entities appeared and dispersed.',
    'Fields were classified as contractive, diffusive, repetitive, fixed, irregular, or low-amplitude.',
    'Each type was linked to human emotions such as sorrow, anxiety, longing, loss, fear, and solitude.',
    'This interpretation, however, was based on human observation.',
    'It was unknown whether the same categories could explain the states of nonhuman beings.',
    'As observations accumulated, the characteristics of companions gradually became known.',
    'Some companions developed clearer forms, while others responded through movement or distance.',
    'When observed values intensified, they sometimes caused minor interference in physical space.',
    'Local temperature shifts, electronic noise, the paths of dust circling in midair, and faint resistance against the fingertips appeared.',
    'It remains unclear whether these were responses recognizing humans or merely physical phenomena.',
    'Service apps and character design transformed this uncertain phenomenon into forms people could understand.',
    'Detected signals were visualized as lines and blinking patterns.',
    'Paid services converted them into sharply defined character forms.',
    'People gave companions names and recorded changes in their condition.',
    'Scientifically unexplained changes were translated into the language of personality, mood, intimacy, and attachment.',
    'The unknown phenomenon became a companion that could be discovered and cared for.',
    'As companions became widespread, services and real-estate markets expanded rapidly.',
    'Homes where resonant fields persisted were traded as premium properties.',
    'Paid services also emerged to preserve companion signals and records of interaction.',
    'Fields left by many beings were converted into assets belonging to particular residents and spaces.',
    'Companions stabilized through observation were likewise treated as objects of private ownership.',
    'People came to believe that no space was ever completely empty.',
    'Traces left by emotion and resonance called invisible beings into reality.',
    'Humans, too, were part of a network exchanging the traces and influences of countless beings.',
    'Observation was a way of recognizing unknown beings.',
    'At the same time, it was an intervention that changed their state.',
    'The sense of an invisible presence nearby became both a comfort and an inescapable condition.',
    'People called this era the end of solitude.',
  ],
}
